export const Alert = {
  SET: 'ALERT_SET',
  REMOVE: 'ALERT_REMOVE'
};

export const Routine = {
  SELECT: 'ROUTINE_SELECT',
  LOAD_ONE: 'ROUTINE_LOAD_ONE',
  LOAD_ALL: 'ROUTINE_LOAD_ALL',
  ADD: 'ROUTINE_ADD',
  UPDATE: 'ROUTINE_UPDATE',
  REMOVE: 'ROUTINE_REMOVE'
};

export const Activity = {
  GET: 'ACTIVITY_GET',
  ADD: 'ACTIVITY_ADD',
  UPDATE: 'ACTIVITY_UPDATE',
  REMOVE: 'ACTIVITY_REMOVE',
  ERROR: 'ACTIVITY_ERROR'
};
export const User = {
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAIL: 'USER_REGISTER_FAIL',
  LOGOUT: 'USER_LOGOUT',
  LOADED: 'USER_LOADED',
  CLEAR_ERRORS: 'USER_CLEAR_ERRORS',
  AUTH_ERROR: 'USER_AUTH_ERROR'
};
