export const Alert = {
  SET: 'SET',
  REMOVE: 'REMOVE'
};

export const Routine = {
  SELECT: 'SELECT',
  LOAD_ONE: 'LOAD_ONE',
  LOAD_ALL: 'LOAD_ALL',
  ADD: 'ADD',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE'
};

export const Activity = {
  GET: 'GET',
  ADD: 'ADD',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
  ERROR: 'ERROR'
};
export const User = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',
  LOADED: 'LOADED',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  AUTH_ERROR: 'AUTH_ERROR'
};
